services:
  db_postgres_students:
    image: postgres
    container_name: db_postgres_students
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg_students:/var/lib/postgresql/data

  node_app_students:
    container_name: students
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db_postgres_students
    env_file:
      - .env

volumes:
  pg_students:

